// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                      = new(Query)
	OAuthAuthorizationCode *oAuthAuthorizationCode
	OAuthClient            *oAuthClient
	RefreshToken           *refreshToken
	User                   *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	OAuthAuthorizationCode = &Q.OAuthAuthorizationCode
	OAuthClient = &Q.OAuthClient
	RefreshToken = &Q.RefreshToken
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                     db,
		OAuthAuthorizationCode: newOAuthAuthorizationCode(db, opts...),
		OAuthClient:            newOAuthClient(db, opts...),
		RefreshToken:           newRefreshToken(db, opts...),
		User:                   newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	OAuthAuthorizationCode oAuthAuthorizationCode
	OAuthClient            oAuthClient
	RefreshToken           refreshToken
	User                   user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		OAuthAuthorizationCode: q.OAuthAuthorizationCode.clone(db),
		OAuthClient:            q.OAuthClient.clone(db),
		RefreshToken:           q.RefreshToken.clone(db),
		User:                   q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		OAuthAuthorizationCode: q.OAuthAuthorizationCode.replaceDB(db),
		OAuthClient:            q.OAuthClient.replaceDB(db),
		RefreshToken:           q.RefreshToken.replaceDB(db),
		User:                   q.User.replaceDB(db),
	}
}

type queryCtx struct {
	OAuthAuthorizationCode *oAuthAuthorizationCodeDo
	OAuthClient            *oAuthClientDo
	RefreshToken           *refreshTokenDo
	User                   *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		OAuthAuthorizationCode: q.OAuthAuthorizationCode.WithContext(ctx),
		OAuthClient:            q.OAuthClient.WithContext(ctx),
		RefreshToken:           q.RefreshToken.WithContext(ctx),
		User:                   q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
