// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/code-practice-archives/api-demo/internal/model"
)

func newOAuthAuthorizationCode(db *gorm.DB, opts ...gen.DOOption) oAuthAuthorizationCode {
	_oAuthAuthorizationCode := oAuthAuthorizationCode{}

	_oAuthAuthorizationCode.oAuthAuthorizationCodeDo.UseDB(db, opts...)
	_oAuthAuthorizationCode.oAuthAuthorizationCodeDo.UseModel(&model.OAuthAuthorizationCode{})

	tableName := _oAuthAuthorizationCode.oAuthAuthorizationCodeDo.TableName()
	_oAuthAuthorizationCode.ALL = field.NewAsterisk(tableName)
	_oAuthAuthorizationCode.Id = field.NewInt64(tableName, "id")
	_oAuthAuthorizationCode.CreatedAt = field.NewInt64(tableName, "created_at")
	_oAuthAuthorizationCode.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_oAuthAuthorizationCode.DeletedAt = field.NewUint(tableName, "deleted_at")
	_oAuthAuthorizationCode.CodeHash = field.NewString(tableName, "code_hash")
	_oAuthAuthorizationCode.ClientID = field.NewString(tableName, "client_id")
	_oAuthAuthorizationCode.UserID = field.NewInt64(tableName, "user_id")
	_oAuthAuthorizationCode.RedirectURI = field.NewString(tableName, "redirect_uri")
	_oAuthAuthorizationCode.Scope = field.NewString(tableName, "scope")
	_oAuthAuthorizationCode.CodeChallenge = field.NewString(tableName, "code_challenge")
	_oAuthAuthorizationCode.CodeChallengeMethod = field.NewString(tableName, "code_challenge_method")
	_oAuthAuthorizationCode.ExpiresAt = field.NewInt64(tableName, "expires_at")
	_oAuthAuthorizationCode.UsedAt = field.NewInt64(tableName, "used_at")

	_oAuthAuthorizationCode.fillFieldMap()

	return _oAuthAuthorizationCode
}

type oAuthAuthorizationCode struct {
	oAuthAuthorizationCodeDo oAuthAuthorizationCodeDo

	ALL                 field.Asterisk
	Id                  field.Int64
	CreatedAt           field.Int64
	UpdatedAt           field.Int64
	DeletedAt           field.Uint
	CodeHash            field.String
	ClientID            field.String
	UserID              field.Int64
	RedirectURI         field.String
	Scope               field.String
	CodeChallenge       field.String
	CodeChallengeMethod field.String
	ExpiresAt           field.Int64
	UsedAt              field.Int64

	fieldMap map[string]field.Expr
}

func (o oAuthAuthorizationCode) Table(newTableName string) *oAuthAuthorizationCode {
	o.oAuthAuthorizationCodeDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o oAuthAuthorizationCode) As(alias string) *oAuthAuthorizationCode {
	o.oAuthAuthorizationCodeDo.DO = *(o.oAuthAuthorizationCodeDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *oAuthAuthorizationCode) updateTableName(table string) *oAuthAuthorizationCode {
	o.ALL = field.NewAsterisk(table)
	o.Id = field.NewInt64(table, "id")
	o.CreatedAt = field.NewInt64(table, "created_at")
	o.UpdatedAt = field.NewInt64(table, "updated_at")
	o.DeletedAt = field.NewUint(table, "deleted_at")
	o.CodeHash = field.NewString(table, "code_hash")
	o.ClientID = field.NewString(table, "client_id")
	o.UserID = field.NewInt64(table, "user_id")
	o.RedirectURI = field.NewString(table, "redirect_uri")
	o.Scope = field.NewString(table, "scope")
	o.CodeChallenge = field.NewString(table, "code_challenge")
	o.CodeChallengeMethod = field.NewString(table, "code_challenge_method")
	o.ExpiresAt = field.NewInt64(table, "expires_at")
	o.UsedAt = field.NewInt64(table, "used_at")

	o.fillFieldMap()

	return o
}

func (o *oAuthAuthorizationCode) WithContext(ctx context.Context) *oAuthAuthorizationCodeDo {
	return o.oAuthAuthorizationCodeDo.WithContext(ctx)
}

func (o oAuthAuthorizationCode) TableName() string { return o.oAuthAuthorizationCodeDo.TableName() }

func (o oAuthAuthorizationCode) Alias() string { return o.oAuthAuthorizationCodeDo.Alias() }

func (o oAuthAuthorizationCode) Columns(cols ...field.Expr) gen.Columns {
	return o.oAuthAuthorizationCodeDo.Columns(cols...)
}

func (o *oAuthAuthorizationCode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *oAuthAuthorizationCode) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 13)
	o.fieldMap["id"] = o.Id
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["deleted_at"] = o.DeletedAt
	o.fieldMap["code_hash"] = o.CodeHash
	o.fieldMap["client_id"] = o.ClientID
	o.fieldMap["user_id"] = o.UserID
	o.fieldMap["redirect_uri"] = o.RedirectURI
	o.fieldMap["scope"] = o.Scope
	o.fieldMap["code_challenge"] = o.CodeChallenge
	o.fieldMap["code_challenge_method"] = o.CodeChallengeMethod
	o.fieldMap["expires_at"] = o.ExpiresAt
	o.fieldMap["used_at"] = o.UsedAt
}

func (o oAuthAuthorizationCode) clone(db *gorm.DB) oAuthAuthorizationCode {
	o.oAuthAuthorizationCodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o oAuthAuthorizationCode) replaceDB(db *gorm.DB) oAuthAuthorizationCode {
	o.oAuthAuthorizationCodeDo.ReplaceDB(db)
	return o
}

type oAuthAuthorizationCodeDo struct{ gen.DO }

func (o oAuthAuthorizationCodeDo) Debug() *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Debug())
}

func (o oAuthAuthorizationCodeDo) WithContext(ctx context.Context) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o oAuthAuthorizationCodeDo) ReadDB() *oAuthAuthorizationCodeDo {
	return o.Clauses(dbresolver.Read)
}

func (o oAuthAuthorizationCodeDo) WriteDB() *oAuthAuthorizationCodeDo {
	return o.Clauses(dbresolver.Write)
}

func (o oAuthAuthorizationCodeDo) Session(config *gorm.Session) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Session(config))
}

func (o oAuthAuthorizationCodeDo) Clauses(conds ...clause.Expression) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o oAuthAuthorizationCodeDo) Returning(value interface{}, columns ...string) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o oAuthAuthorizationCodeDo) Not(conds ...gen.Condition) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o oAuthAuthorizationCodeDo) Or(conds ...gen.Condition) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o oAuthAuthorizationCodeDo) Select(conds ...field.Expr) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o oAuthAuthorizationCodeDo) Where(conds ...gen.Condition) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o oAuthAuthorizationCodeDo) Order(conds ...field.Expr) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o oAuthAuthorizationCodeDo) Distinct(cols ...field.Expr) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o oAuthAuthorizationCodeDo) Omit(cols ...field.Expr) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o oAuthAuthorizationCodeDo) Join(table schema.Tabler, on ...field.Expr) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o oAuthAuthorizationCodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o oAuthAuthorizationCodeDo) RightJoin(table schema.Tabler, on ...field.Expr) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o oAuthAuthorizationCodeDo) Group(cols ...field.Expr) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o oAuthAuthorizationCodeDo) Having(conds ...gen.Condition) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o oAuthAuthorizationCodeDo) Limit(limit int) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o oAuthAuthorizationCodeDo) Offset(offset int) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o oAuthAuthorizationCodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o oAuthAuthorizationCodeDo) Unscoped() *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Unscoped())
}

func (o oAuthAuthorizationCodeDo) Create(values ...*model.OAuthAuthorizationCode) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o oAuthAuthorizationCodeDo) CreateInBatches(values []*model.OAuthAuthorizationCode, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o oAuthAuthorizationCodeDo) Save(values ...*model.OAuthAuthorizationCode) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o oAuthAuthorizationCodeDo) First() (*model.OAuthAuthorizationCode, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OAuthAuthorizationCode), nil
	}
}

func (o oAuthAuthorizationCodeDo) Take() (*model.OAuthAuthorizationCode, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OAuthAuthorizationCode), nil
	}
}

func (o oAuthAuthorizationCodeDo) Last() (*model.OAuthAuthorizationCode, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OAuthAuthorizationCode), nil
	}
}

func (o oAuthAuthorizationCodeDo) Find() ([]*model.OAuthAuthorizationCode, error) {
	result, err := o.DO.Find()
	return result.([]*model.OAuthAuthorizationCode), err
}

func (o oAuthAuthorizationCodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OAuthAuthorizationCode, err error) {
	buf := make([]*model.OAuthAuthorizationCode, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o oAuthAuthorizationCodeDo) FindInBatches(result *[]*model.OAuthAuthorizationCode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o oAuthAuthorizationCodeDo) Attrs(attrs ...field.AssignExpr) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o oAuthAuthorizationCodeDo) Assign(attrs ...field.AssignExpr) *oAuthAuthorizationCodeDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o oAuthAuthorizationCodeDo) Joins(fields ...field.RelationField) *oAuthAuthorizationCodeDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o oAuthAuthorizationCodeDo) Preload(fields ...field.RelationField) *oAuthAuthorizationCodeDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o oAuthAuthorizationCodeDo) FirstOrInit() (*model.OAuthAuthorizationCode, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OAuthAuthorizationCode), nil
	}
}

func (o oAuthAuthorizationCodeDo) FirstOrCreate() (*model.OAuthAuthorizationCode, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OAuthAuthorizationCode), nil
	}
}

func (o oAuthAuthorizationCodeDo) FindByPage(offset int, limit int) (result []*model.OAuthAuthorizationCode, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o oAuthAuthorizationCodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o oAuthAuthorizationCodeDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o oAuthAuthorizationCodeDo) Delete(models ...*model.OAuthAuthorizationCode) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *oAuthAuthorizationCodeDo) withDO(do gen.Dao) *oAuthAuthorizationCodeDo {
	o.DO = *do.(*gen.DO)
	return o
}
