// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/code-practice-archives/api-demo/internal/model"
)

func newOAuthClient(db *gorm.DB, opts ...gen.DOOption) oAuthClient {
	_oAuthClient := oAuthClient{}

	_oAuthClient.oAuthClientDo.UseDB(db, opts...)
	_oAuthClient.oAuthClientDo.UseModel(&model.OAuthClient{})

	tableName := _oAuthClient.oAuthClientDo.TableName()
	_oAuthClient.ALL = field.NewAsterisk(tableName)
	_oAuthClient.Id = field.NewInt64(tableName, "id")
	_oAuthClient.CreatedAt = field.NewInt64(tableName, "created_at")
	_oAuthClient.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_oAuthClient.DeletedAt = field.NewUint(tableName, "deleted_at")
	_oAuthClient.ClientID = field.NewString(tableName, "client_id")
	_oAuthClient.ClientSecretHash = field.NewString(tableName, "client_secret_hash")
	_oAuthClient.Name = field.NewString(tableName, "name")
	_oAuthClient.RedirectURIs = field.NewString(tableName, "redirect_uris")

	_oAuthClient.fillFieldMap()

	return _oAuthClient
}

type oAuthClient struct {
	oAuthClientDo oAuthClientDo

	ALL              field.Asterisk
	Id               field.Int64
	CreatedAt        field.Int64
	UpdatedAt        field.Int64
	DeletedAt        field.Uint
	ClientID         field.String
	ClientSecretHash field.String
	Name             field.String
	RedirectURIs     field.String

	fieldMap map[string]field.Expr
}

func (o oAuthClient) Table(newTableName string) *oAuthClient {
	o.oAuthClientDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o oAuthClient) As(alias string) *oAuthClient {
	o.oAuthClientDo.DO = *(o.oAuthClientDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *oAuthClient) updateTableName(table string) *oAuthClient {
	o.ALL = field.NewAsterisk(table)
	o.Id = field.NewInt64(table, "id")
	o.CreatedAt = field.NewInt64(table, "created_at")
	o.UpdatedAt = field.NewInt64(table, "updated_at")
	o.DeletedAt = field.NewUint(table, "deleted_at")
	o.ClientID = field.NewString(table, "client_id")
	o.ClientSecretHash = field.NewString(table, "client_secret_hash")
	o.Name = field.NewString(table, "name")
	o.RedirectURIs = field.NewString(table, "redirect_uris")

	o.fillFieldMap()

	return o
}

func (o *oAuthClient) WithContext(ctx context.Context) *oAuthClientDo {
	return o.oAuthClientDo.WithContext(ctx)
}

func (o oAuthClient) TableName() string { return o.oAuthClientDo.TableName() }

func (o oAuthClient) Alias() string { return o.oAuthClientDo.Alias() }

func (o oAuthClient) Columns(cols ...field.Expr) gen.Columns { return o.oAuthClientDo.Columns(cols...) }

func (o *oAuthClient) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *oAuthClient) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 8)
	o.fieldMap["id"] = o.Id
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["deleted_at"] = o.DeletedAt
	o.fieldMap["client_id"] = o.ClientID
	o.fieldMap["client_secret_hash"] = o.ClientSecretHash
	o.fieldMap["name"] = o.Name
	o.fieldMap["redirect_uris"] = o.RedirectURIs
}

func (o oAuthClient) clone(db *gorm.DB) oAuthClient {
	o.oAuthClientDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o oAuthClient) replaceDB(db *gorm.DB) oAuthClient {
	o.oAuthClientDo.ReplaceDB(db)
	return o
}

type oAuthClientDo struct{ gen.DO }

func (o oAuthClientDo) Debug() *oAuthClientDo {
	return o.withDO(o.DO.Debug())
}

func (o oAuthClientDo) WithContext(ctx context.Context) *oAuthClientDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o oAuthClientDo) ReadDB() *oAuthClientDo {
	return o.Clauses(dbresolver.Read)
}

func (o oAuthClientDo) WriteDB() *oAuthClientDo {
	return o.Clauses(dbresolver.Write)
}

func (o oAuthClientDo) Session(config *gorm.Session) *oAuthClientDo {
	return o.withDO(o.DO.Session(config))
}

func (o oAuthClientDo) Clauses(conds ...clause.Expression) *oAuthClientDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o oAuthClientDo) Returning(value interface{}, columns ...string) *oAuthClientDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o oAuthClientDo) Not(conds ...gen.Condition) *oAuthClientDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o oAuthClientDo) Or(conds ...gen.Condition) *oAuthClientDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o oAuthClientDo) Select(conds ...field.Expr) *oAuthClientDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o oAuthClientDo) Where(conds ...gen.Condition) *oAuthClientDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o oAuthClientDo) Order(conds ...field.Expr) *oAuthClientDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o oAuthClientDo) Distinct(cols ...field.Expr) *oAuthClientDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o oAuthClientDo) Omit(cols ...field.Expr) *oAuthClientDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o oAuthClientDo) Join(table schema.Tabler, on ...field.Expr) *oAuthClientDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o oAuthClientDo) LeftJoin(table schema.Tabler, on ...field.Expr) *oAuthClientDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o oAuthClientDo) RightJoin(table schema.Tabler, on ...field.Expr) *oAuthClientDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o oAuthClientDo) Group(cols ...field.Expr) *oAuthClientDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o oAuthClientDo) Having(conds ...gen.Condition) *oAuthClientDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o oAuthClientDo) Limit(limit int) *oAuthClientDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o oAuthClientDo) Offset(offset int) *oAuthClientDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o oAuthClientDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *oAuthClientDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o oAuthClientDo) Unscoped() *oAuthClientDo {
	return o.withDO(o.DO.Unscoped())
}

func (o oAuthClientDo) Create(values ...*model.OAuthClient) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o oAuthClientDo) CreateInBatches(values []*model.OAuthClient, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o oAuthClientDo) Save(values ...*model.OAuthClient) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o oAuthClientDo) First() (*model.OAuthClient, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OAuthClient), nil
	}
}

func (o oAuthClientDo) Take() (*model.OAuthClient, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OAuthClient), nil
	}
}

func (o oAuthClientDo) Last() (*model.OAuthClient, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OAuthClient), nil
	}
}

func (o oAuthClientDo) Find() ([]*model.OAuthClient, error) {
	result, err := o.DO.Find()
	return result.([]*model.OAuthClient), err
}

func (o oAuthClientDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OAuthClient, err error) {
	buf := make([]*model.OAuthClient, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o oAuthClientDo) FindInBatches(result *[]*model.OAuthClient, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o oAuthClientDo) Attrs(attrs ...field.AssignExpr) *oAuthClientDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o oAuthClientDo) Assign(attrs ...field.AssignExpr) *oAuthClientDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o oAuthClientDo) Joins(fields ...field.RelationField) *oAuthClientDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o oAuthClientDo) Preload(fields ...field.RelationField) *oAuthClientDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o oAuthClientDo) FirstOrInit() (*model.OAuthClient, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OAuthClient), nil
	}
}

func (o oAuthClientDo) FirstOrCreate() (*model.OAuthClient, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OAuthClient), nil
	}
}

func (o oAuthClientDo) FindByPage(offset int, limit int) (result []*model.OAuthClient, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o oAuthClientDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o oAuthClientDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o oAuthClientDo) Delete(models ...*model.OAuthClient) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *oAuthClientDo) withDO(do gen.Dao) *oAuthClientDo {
	o.DO = *do.(*gen.DO)
	return o
}
