// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/code-practice-archives/api-demo/internal/config"
	"github.com/code-practice-archives/api-demo/internal/handler"
	"github.com/code-practice-archives/api-demo/internal/pkg/database"
	"github.com/code-practice-archives/api-demo/internal/repository"
	"github.com/code-practice-archives/api-demo/internal/router"
	"github.com/code-practice-archives/api-demo/internal/server"
	"github.com/code-practice-archives/api-demo/internal/service"
)

// Injectors from wire.go:

func initializeServer(cfg *config.Config) (*server.Server, func(), error) {
	serverConfig := cfg.Server
	databaseConfig := cfg.DB
	db, err := database.Open(databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	repositories := repository.New(db)
	jwtxConfig := cfg.JWT
	manager := provideJWTManager(jwtxConfig)
	loginjailConfig := cfg.Jail
	redisxConfig := cfg.Redis
	client, cleanup, err := provideRedis(redisxConfig)
	if err != nil {
		return nil, nil, err
	}
	jail, err := provideLoginJail(loginjailConfig, client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	loggerConfig := cfg.Log
	logger, cleanup2, err := provideLogger(loggerConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	services := service.New(repositories, manager, jail, logger)
	authHandler := handler.NewAuthHandler(services)
	handlers := handler.New(authHandler)
	engine := router.New(handlers, manager, logger)
	httpServer := provideHTTPServer(serverConfig, engine)
	serverServer := server.New(httpServer, logger)
	return serverServer, func() {
		cleanup2()
		cleanup()
	}, nil
}
